#!/bin/bash

export SOLVERLAB_INSTALL=@CMAKE_INSTALL_PREFIX@
export PETSC_DIR=@PETSC_INSTALL@
export PETSC_ARCH=@PETSC_ARCH@
export PETSC_INCLUDES=@PETSC_INCLUDES_INSTALL@
export PETSC_LIBRARIES=@PETSC_DIR@/@PETSC_ARCH@/lib
export PETSC4PY_ROOT_DIR=@PETSC4PY_ROOT_DIR@
export SLEPC4PY_ROOT_DIR=@SLEPC4PY_ROOT_DIR@
export MEDFILE_ROOT_DIR=@MEDFILE_ROOT_DIR@
export MEDFILE_INCLUDE_DIRS=@MEDFILE_INCLUDE_DIRS@
export MEDFILE_LIBRARIES=@MEDFILE_LIBRARIES_INSTALL@
export MEDCOUPLING_ROOT_DIR=@MEDCOUPLING_ROOT_DIR@
export MEDCOUPLING_INCLUDE_DIR=@MEDCOUPLING_INCLUDE_DIR@
export MEDCOUPLING_LIBRARIES=@MEDCOUPLING_LIBRARIES@
export PV_LIB_DIR=@PV_LIB_DIR@
export PV_PYTHON_DIR=@PV_PYTHON_DIR@
export HDF5_ROOT=@HDF5_ROOT@

export SOLVERLAB=$SOLVERLAB_INSTALL/bin/Executable/COREFLOWSMainExe
export LD_LIBRARY_PATH=$SOLVERLAB_INSTALL/lib:$PETSC_DIR/lib:$PETSC_DIR/$PETSC_ARCH/lib:$MEDCOUPLING_LIBRARIES:$MEDFILE_ROOT_DIR/lib:$HDF5_ROOT/lib:$PV_LIB_DIR:$LD_LIBRARY_PATH
export PYTHONPATH=$SOLVERLAB_INSTALL/bin:$SOLVERLAB_INSTALL/bin/cdmath:$SOLVERLAB_INSTALL/bin/cdmath/postprocessing:$SOLVERLAB_INSTALL/bin/coreflows:$SOLVERLAB_INSTALL/lib:$SOLVERLAB_INSTALL/lib/cdmath:$SOLVERLAB_INSTALL/lib/coreflows:$PETSC_DIR/$PETSC_ARCH/lib:$PETSC_DIR/lib:$PETSC4PY_ROOT_DIR:$PETSC4PY_ROOT_DIR/lib/$PETSC_ARCH:$SLEPC4PY_ROOT_DIR:$SLEPC4PY_ROOT_DIR/lib/$PETSC_ARCH:$MEDCOUPLING_LIBRARIES:$MEDCOUPLING_LIBRARIES/python@Python_VERSION_MAJOR@.@Python_VERSION_MINOR@/site-packages/:$MEDFILE_ROOT_DIR/lib:$HDF5_ROOT/lib:$PV_PYTHON_DIR:$PYTHONPATH

if [ @SOLVERLAB_WITH_MPI@ = ON ] # test SOLVERLAB_WITH_MPI
then
  export mpirun=$PETSC_DIR/$PETSC_ARCH/bin/mpirun
  export mpiexec=$PETSC_DIR/$PETSC_ARCH/bin/mpiexec
  export MPI4PY_ROOT_DIR=@MPI4PY_ROOT_DIR@
  export PYTHONPATH=$MPI4PY_ROOT_DIR:$PYTHONPATH
fi

if [ @PRELOAD_NETCDF_ON_UBUNTU20@ = ON ]  # test PRELOAD_NETCDF_ON_UBUNTU20
then
    export  LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnetcdf.so
fi

export SOLVERLAB_ROOT_DIR=$SOLVERLAB_INSTALL

# TODO 220114 Have to be tested because needs a preexisting python3 context with PyQt5/numpy/matplotlib/paraview etc. compatible!
# this is PROTOTYPING of dir PACKAGESPY to get solverlabGUI (standalone installation, not in salome context)

# PACKAGESPY in SOLVERLAB_INSTALL as salome usage with PACKAGESPY_ROOT_DIR as version wambeke
if [ -d ${SOLVERLAB_INSTALL}/PACKAGESPY ] # test existing dir PACKAGESPY to get solverlabGUI standalone 
then
    export PACKAGESPY_ROOT_DIR=${SOLVERLAB_INSTALL}/PACKAGESPY
    export SOLVERLAB_ROOT_DIR=${PACKAGESPY_ROOT_DIR}/pythonAppliMatix/solverlabGUI
    export PYTHONPATH=${PACKAGESPY_ROOT_DIR}/pythonAppliMatix:$PYTHONPATH
    export PATH=${PACKAGESPY_ROOT_DIR}/pythonAppliMatix:$PATH
    export SOLVERLABGUI=${SOLVERLAB_ROOT_DIR}/solverlabGUI  # main initial python script
    echo "solverlabGUI installation Wambeke as salome"
    echo "To launch solverlabGUI type '\$SOLVERLABGUI --gui'"
fi

# PACKAGESPY in SOLVERLAB_INSTALL as standalone version Michael
if [ @SOLVERLAB_WITH_GUI@ = ON ] 
then
  export SOLVERLABGUI=$SOLVERLAB_INSTALL/bin/salome/solverlabGUI
  export SOLVERLAB_ROOT_DIR=$SOLVERLAB_INSTALL/bin/salome/
  export PACKAGESPY_ROOT_DIR=@PACKAGESPY_ROOT_DIR@
  echo "solverlabGUI installation Michael as salome"
  echo "To launch solverlabGUI type '\$SOLVERLABGUI --gui'"
fi
