/*
 * LinearSolver.hxx
 *
 *  Created on: 13 April. 2013
 *      Authors: CDMATH
 */

#ifndef LINEARSOLVER_HXX_
#define LINEARSOLVER_HXX_

#include <string>
#include <vector>

#include <petsc.h>

#include "GenericMatrix.hxx"
#include "Vector.hxx"


class LinearSolver
{
public: //----------------------------------------------------------------

	LinearSolver ( void ) ;

	~LinearSolver ( void ) ;

	LinearSolver( const GenericMatrix& matrix,
			const Vector& secondMember,
			int numberMaxOfIter,
			double tol,
			std::string nameOfMethod,
			std::string nameOfPc="" );

	LinearSolver( const GenericMatrix& matrix,
			const std::vector<double>& secondMember,
			int numberMaxOfIter,
			double tol,
			std::string nameOfMethod,
			std::string nameOfPc="" );

	//This constructor reads the matrix and the right hand side contained in a binary file generated by PETSc or HDF5
	LinearSolver( const std::string filename, 
			int numberMaxOfIter,
			double tol,
			std::string nameOfMethod,
			std::string nameOfPc="" ,
			bool hdf5BbinaryMode = false);

	const LinearSolver& operator= ( LinearSolver& linearSolver ) ;

	LinearSolver ( LinearSolver& LS ) ;

	void setMethod(std::string nameOfMethod) ;

	void setPreconditioner(std::string pc) ;

	void setComputeConditionNumber(bool display=true);
    double getConditionNumber() const;
    
	int getNumberOfIter( void ) const ;

	bool getStatus( void ) const ;

	double getResidu( void ) const ;

	double getTolerance( void ) const ;

	int getNumberMaxOfIter( void ) const ;

	void setTolerance(double tol) ;

	void setNumberMaxOfIter(int numberMaxOfIter) ;

	Vector getSndMember( void ) const ;

	std::string getNameOfMethod( void ) const ;

	std::string getNameOfPc( void ) const ;

	Vector solve( Vector X = Vector(0) ) ;
	/* Compute the residual P(AX-b) where P is the preconditioner and X is an input vector */
	Vector getResidual( Vector X = Vector(0) ) const;
	/* Compute the initial residual P(-b) where P is the preconditioner*/
	Vector getInitialResidual( ) const;
	/* Compute the final residual P(AX-b) where P is the preconditioner and X is a the solution vector */
	Vector getFinalResidual( ) const;

	void setMatrix(const GenericMatrix& matrix) ;
	void setMatrix(std::string filename, bool hdf5BinaryMode=false) ;//Reads matrix contained in a binary file generated by PETSc or HDF5

	void setSndMember(const Vector& secondMember) ;
	void setSndMember(std::string filename, bool hdf5BinaryMode=false) ;//Reads RHS vector contained in a binary file generated by PETSc or HDF5
	
	void saveMatrix(            std::string filename, bool binaryMode=false);//Writes matrix to a ascii or binary file
	void saveSndMember(         std::string filename, bool binaryMode=false);//Writes RHS vector to a ascii or binary file
	void saveMatrixAndSndMember(std::string filename, bool binaryMode=false);//Writes matrix and RHS vector to a ascii or binary file

	void setMatrixIsSingular(bool sing=true) ;

	bool isMatrixSingular( void ) const;

	bool isSparseMatrix( void ) const ;

	Mat getPetscMatrix() const ;
	Vec getPetscVector() const ;
	void viewPetscMatrix() const ;
	void viewPetscRHS() const;
	double getPetscMatValue(int i, int j) const;
	double getPetscRHSValue(int i) const 	;

	void kspDuplicate(const KSP source, const Mat mat, KSP destination) const;
	void precDuplicate(const PC source, const KSP ksp, PC destination) const;
	KSP getPetscKsp() ;
	PC getPetscPc() ;
    	/** \fn setPetscOptions
	 * \brief sets the options used in PETSc global database
	 * @param Any available option in PETSc (See PETSc documentation)
	 */
	void setPetscOptions(const char petscOptions[], const char value[] = NULL){PetscOptionsSetValue(NULL, petscOptions, value);}


private: //----------------------------------------------------------------

	void setLinearSolver(const GenericMatrix& matrix, const Vector& secondMember) ;
	void setLinearSolver(const std::string filename, bool hdf5BinaryMode = false) ;//Sets matrix and RHS contained in a binary file generated by PETSc or HDF5
	void setMatrixAndSndMember( const std::string filename, bool hdf5BinaryMode = false);//Reads matrix and RHS that were saved in the same binary file using function saveMatrixAndSndMember
	
	void setKsp() ;
	Vec getKSPSolution() const { return _solution; }
	
	Vec vectorToVec( const Vector& myVector ) const ;

	Vector vecToVector(const Vec& vec) const ;

	double _tol;
	int _numberMaxOfIter;
	double _residu;
	bool _convergence;
	int _numberOfIter;
	bool _isSingular;
	bool _isSparseMatrix;
	bool _computeConditionNumber;
	double _conditionNumber;
	std::string _nameOfPc;
	std::string _nameOfMethod;
	Vector _secondMember;
	Mat _mat;
	Vec _smb;
	PC _prec;
	KSP _ksp;
	Vec _solution;//store the initial guess before solve and the solution after solve

};

#endif /* LINEARSOLVER_HXX_ */
