# -*- rpm-spec -*-
BuildRoot:      /tmp
Summary:        Numerical Analysis toolbox
Name:           cdmath
Version:        0.4
Release:        1
License:        Open Source
Group:          Development/Science
Vendor:         CEA Saclay
Packager:       Michael Ndjinga <firstname.lastname@cea.fr>
Source:         cdmath-%{version}.tar.gz
URL:            https://github.com/mndjinga/CDMATH/archive/master.zip

BuildRequires: 	cmake, gcc-c++, hdf5-devel, petsc-devel, openmpi-devel
Requires: 		hdf5, petsc, openmpi

%description
CDMATH is a geometrical and numerical toolbox designed for numerical analysts who work on the discretisation of partial differential equations on general shapes and meshes and who would rather focus on high-level scripting of finite elements and finite volume methods. The library originates from [CDMATH](http://cdmath.jimdo.com), a collaborative workgroup with the same name. It is based on the [MEDcoupling](http://docs.salome-platform.org/latest/dev/MEDCoupling/index.html) library of the [SALOME](http://www.salome-platform.org/) project for the handling of meshes and fields, and on the library [PETSC](https://www.mcs.anl.gov/petsc/) for the handling of matrices and linear solvers.

%prep
%setup -q

%build
cmake -DCMAKE_INSTALL_PREFIX=/opt -DCMAKE_BUILD_TYPE=Release .
make

%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

%post

%postun

%pre

%preun

%files
%defattr(-,root,root,-)
"/opt/lib/libinterpkernel.so"
"/opt/lib/libbase.so"
"/opt/lib/libmedcoupling.so"
"/opt/lib/libmesh.so"
"/opt/lib/libmedcouplingremapper.so"
"/opt/lib/libmedloader.so"
"/opt/lib/libmedC.so"
%dir "/opt/share/cmake"
%dir "/opt/share/cmake/MEDFile"
"/opt/share/cmake/MEDFile/MEDFileConfig.cmake"
"/opt/share/cmake/MEDFile/MEDFileConfigVersion.cmake"
%dir "/opt/share/doc/cdmath"
%dir "/opt/share/doc/cdmath/examples"
%dir "/opt/share/doc/cdmath/examples/thermique1d"
"/opt/share/doc/cdmath/examples/thermique1d/makefile"
"/opt/share/doc/cdmath/examples/thermique1d/main.cxx"
%dir "/opt/share/doc/cdmath/examples/transport2d_ns"
"/opt/share/doc/cdmath/examples/transport2d_ns/main2.cxx"
"/opt/share/doc/cdmath/examples/transport2d_ns/MeshTri.med"
"/opt/share/doc/cdmath/examples/transport2d_ns/makefile"
"/opt/share/doc/cdmath/examples/transport2d_ns/main.py"
"/opt/share/doc/cdmath/examples/transport2d_ns/main.cxx"
%dir "/opt/share/doc/cdmath/examples/transport2d_s"
"/opt/share/doc/cdmath/examples/transport2d_s/makefile"
"/opt/share/doc/cdmath/examples/transport2d_s/main.py"
"/opt/share/doc/cdmath/examples/transport2d_s/main.cxx"
%dir "/opt/share/doc/cdmath/examples/transport1d"
"/opt/share/doc/cdmath/examples/transport1d/makefile"
"/opt/share/doc/cdmath/examples/transport1d/main.py"
"/opt/share/doc/cdmath/examples/transport1d/main.cxx"
"/opt/include/MEDCouplingNormalizedCartesianMesh.txx"
"/opt/include/InterpKernelGeo2DEdgeLin.hxx"
"/opt/include/TargetIntersector.hxx"
"/opt/include/MEDCouplingDefinitionTime.hxx"
"/opt/include/CurveIntersectorP1P1.txx"
"/opt/include/InterpKernelMatrix.hxx"
"/opt/include/medlibrary.h"
"/opt/include/PolyhedronIntersectorP1P1.txx"
"/opt/include/Barycentric3DIntersectorP1P1.txx"
"/opt/include/CurveIntersector.hxx"
"/opt/include/InterpKernelStlExt.hxx"
"/opt/include/DoubleTab.hxx"
"/opt/include/MEDCouplingFieldOverTime.hxx"
"/opt/include/MeshRegion.txx"
"/opt/include/GenMathFormulae.hxx"
"/opt/include/IntTab.hxx"
"/opt/include/MEDCouplingCartesianAMRMesh.hxx"
"/opt/include/Log.hxx"
"/opt/include/MEDLoaderBase.hxx"
"/opt/include/SauvReader.hxx"
"/opt/include/medfilter.h"
"/opt/include/medlink.h"
"/opt/include/VolSurfFormulae.hxx"
"/opt/include/PlanarIntersectorP0P0.txx"
"/opt/include/InterpKernelGeo2DQuadraticPolygon.hxx"
"/opt/include/TransformedTriangleInline.hxx"
"/opt/include/PlanarIntersectorP1P0.hxx"
"/opt/include/NormalizedGeometricTypes"
%dir "/opt/include/2.3.6"
"/opt/include/2.3.6/med23v30_proto.h"
"/opt/include/2.3.6/medC_win_dll.h"
"/opt/include/2.3.6/MEDerreur.hxx"
"/opt/include/2.3.6/med_utils.h"
"/opt/include/2.3.6/med_exit_if.h"
"/opt/include/2.3.6/med.h"
"/opt/include/2.3.6/med23v30.h"
"/opt/include/2.3.6/med.hf"
"/opt/include/2.3.6/med_proto.h"
"/opt/include/InterpKernelFunction.hxx"
"/opt/include/Interpolation3D2D.txx"
"/opt/include/BBTreeDst.txx"
"/opt/include/MEDCouplingMesh.hxx"
"/opt/include/Interpolation3DSurf.hxx"
"/opt/include/InterpKernelAutoPtr.hxx"
"/opt/include/MEDFileField.hxx"
"/opt/include/InterpKernelMatrixTools.hxx"
"/opt/include/CurveIntersectorP0P1.hxx"
"/opt/include/InterpKernelExprParser.hxx"
"/opt/include/PolygonAlgorithms.hxx"
"/opt/include/MEDCouplingAMRAttribute.hxx"
"/opt/include/MEDCouplingTimeDiscretization.hxx"
"/opt/include/INTERPKERNELDefines.hxx"
"/opt/include/Mesh.hxx"
"/opt/include/MEDFileFieldOverView.hxx"
"/opt/include/InterpKernelGaussCoords.hxx"
"/opt/include/Interpolation.hxx"
"/opt/include/MEDFileMeshReadSelector.hxx"
"/opt/include/Interpolation3D.hxx"
"/opt/include/Interpolation3D.txx"
"/opt/include/IntersectorCU3D.txx"
"/opt/include/SauvUtilities.hxx"
"/opt/include/InterpKernelGeo2DComposedEdge.hxx"
"/opt/include/GenericMatrix.hxx"
"/opt/include/PointLocatorAlgos.txx"
"/opt/include/CurveIntersectorP1P0.txx"
"/opt/include/Interpolation1D.hxx"
"/opt/include/PointLocator3DIntersectorP1P1.txx"
"/opt/include/MEDCouplingFieldDouble.hxx"
"/opt/include/BoxSplittingOptions.hxx"
"/opt/include/Polyhedron3D2DIntersectorP0P0.txx"
"/opt/include/InterpolationCurve.txx"
"/opt/include/InterpKernelGeo2DEdge.txx"
"/opt/include/Intersector3DP0P0.txx"
"/opt/include/Intersector3D.hxx"
"/opt/include/PointLocator3DIntersectorP0P1.hxx"
"/opt/include/Intersector3DP1P1.txx"
"/opt/include/PlanarIntersectorP0P1PL.txx"
"/opt/include/PlanarIntersectorP0P0.hxx"
"/opt/include/IntersectorCU.hxx"
"/opt/include/MEDCouplingRemapper.hxx"
"/opt/include/medC_win_dll.h"
"/opt/include/InterpKernelAsmX86.hxx"
"/opt/include/IntersectorCU2D.hxx"
"/opt/include/Matrix.hxx"
"/opt/include/MEDCouplingMatrix.hxx"
"/opt/include/PointLocator2DIntersector.txx"
"/opt/include/med.hf77"
"/opt/include/InterpolationPlanar.hxx"
"/opt/include/PlanarIntersectorP0P1Bary.txx"
"/opt/include/MEDCouplingRefCountObject.hxx"
"/opt/include/MEDCouplingAutoRefCountObjectPtr.hxx"
"/opt/include/InterpKernelValue.hxx"
"/opt/include/ConvexIntersector.txx"
"/opt/include/Cell.hxx"
"/opt/include/Interpolation2DCurve.hxx"
"/opt/include/InterpolationOptions.hxx"
"/opt/include/Intersector3DP1P1.hxx"
"/opt/include/PolyhedronIntersectorP1P0Bary.txx"
"/opt/include/PolyhedronIntersectorP1P0Bary.hxx"
"/opt/include/InterpKernelHashMap.hxx"
"/opt/include/Intersector3DP1P0Bary.txx"
"/opt/include/InterpKernelGeo2DPrecision.hxx"
"/opt/include/InterpolationCurve.hxx"
"/opt/include/PlanarIntersectorP1P1.hxx"
"/opt/include/CurveIntersector.txx"
"/opt/include/TetraAffineTransform.hxx"
"/opt/include/med_err.h"
"/opt/include/PolyhedronIntersectorP1P0.txx"
"/opt/include/InterpKernelGeo2DAbstractEdge.hxx"
"/opt/include/medparameter.h"
"/opt/include/PolyhedronIntersectorP0P0.hxx"
"/opt/include/VTKNormalizedUnstructuredMesh.txx"
"/opt/include/UnitTetraIntersectionBary.hxx"
"/opt/include/PlanarIntersectorP0P1.hxx"
"/opt/include/MEDCouplingExtrudedMesh.hxx"
"/opt/include/IntersectorCU1D.txx"
"/opt/include/MEDCoupling.hxx"
"/opt/include/CurveIntersectorP1P0.hxx"
"/opt/include/InterpKernelGeo2DEdgeArcCircle.hxx"
"/opt/include/PlanarIntersectorP1P1.txx"
"/opt/include/MEDCouplingNormalizedCartesianMesh.hxx"
"/opt/include/InterpolationCC.hxx"
"/opt/include/TranslationRotationMatrix.hxx"
"/opt/include/PolygonAlgorithms.txx"
"/opt/include/MEDFileParameter.hxx"
"/opt/include/medinterp.h"
"/opt/include/PointLocator3DIntersectorP1P1.hxx"
"/opt/include/PlanarIntersectorP1P0.txx"
"/opt/include/InterpKernelGeo2DBounds.hxx"
"/opt/include/InterpKernelException.hxx"
"/opt/include/IntegralUniformIntersector.txx"
"/opt/include/PolyhedronIntersectorP1P0.hxx"
"/opt/include/InterpKernelHashTable.hxx"
"/opt/include/PolyhedronIntersectorP0P1.txx"
"/opt/include/MEDCouplingMultiFields.hxx"
"/opt/include/MEDFileBasis.hxx"
"/opt/include/BBTreePts.txx"
"/opt/include/PlanarIntersectorP1P0PL.txx"
"/opt/include/PlanarIntersectorP1P1PL.txx"
"/opt/include/MEDCouplingField.hxx"
"/opt/include/InterpolationUtils.hxx"
"/opt/include/CellModel.hxx"
"/opt/include/Intersector3DP0P0.hxx"
"/opt/include/MEDCouplingStructuredMesh.hxx"
"/opt/include/SparseMatrix.hxx"
"/opt/include/MEDerreur.hxx"
"/opt/include/med_utils.h"
"/opt/include/medfield.h"
"/opt/include/Barycentric3DIntersectorP1P1.hxx"
"/opt/include/IntegralUniformIntersector.hxx"
"/opt/include/Intersector3DP0P1.hxx"
"/opt/include/PlanarIntersectorP1P0Bary.hxx"
"/opt/include/TriangulationIntersector.hxx"
"/opt/include/CurveIntersectorP0P1.txx"
"/opt/include/PointLocator3DIntersectorP0P0.txx"
"/opt/include/InterpKernelUtilities.hxx"
"/opt/include/MEDCouplingNatureOfField.hxx"
"/opt/include/PlanarIntersectorP0P1PL.hxx"
"/opt/include/SauvWriter.hxx"
"/opt/include/InterpolationCU.txx"
"/opt/include/medequivalence.h"
"/opt/include/medsubdomain.h"
"/opt/include/ConvexIntersector.hxx"
"/opt/include/VolSurfUser.hxx"
"/opt/include/Planar2D1DIntersectorP0P0.txx"
"/opt/include/PolyhedronIntersectorP0P0.txx"
"/opt/include/InterpKernelCellSimplify.hxx"
"/opt/include/Vector.hxx"
"/opt/include/MEDCouplingCurveLinearMesh.hxx"
"/opt/include/MEDCouplingGaussLocalization.hxx"
"/opt/include/InterpKernelGeo2DNode.hxx"
"/opt/include/med_parameter.hf"
"/opt/include/MEDLoaderDefines.hxx"
"/opt/include/Intersector3DP1P0Bary.hxx"
"/opt/include/MeshRegion.hxx"
"/opt/include/CurveIntersectorP0P0.hxx"
"/opt/include/DirectedBoundingBox.hxx"
"/opt/include/InterpKernelUnit.hxx"
"/opt/include/MeshElement.txx"
"/opt/include/MEDCouplingUMesh.hxx"
"/opt/include/SplitterTetra.hxx"
"/opt/include/SplitterTetra.txx"
"/opt/include/MeshElement.hxx"
"/opt/include/med_exit_if.h"
"/opt/include/med.hf90"
"/opt/include/InterpolationPlanar.txx"
"/opt/include/PointLocator3DIntersectorP0P1.txx"
"/opt/include/Intersector3D.txx"
"/opt/include/MEDFileMeshElt.hxx"
"/opt/include/medfile.h"
"/opt/include/Geometric2DIntersector.hxx"
"/opt/include/MEDCouplingNatureOfFieldEnum"
"/opt/include/Planar2D1DIntersectorP0P0.hxx"
"/opt/include/PlanarIntersectorP1P1PL.hxx"
"/opt/include/MEDFileData.hxx"
"/opt/include/CurveIntersectorP1P1.hxx"
"/opt/include/Interpolation2D1D.txx"
"/opt/include/PolyhedronIntersectorP1P1.hxx"
"/opt/include/IntersectorCU.txx"
"/opt/include/PlanarIntersectorP1P0PL.hxx"
"/opt/include/medprofile.h"
"/opt/include/RegionNode.hxx"
"/opt/include/SauvMedConvertor.hxx"
"/opt/include/MEDLoader.hxx"
"/opt/include/MEDCouplingPointSet.hxx"
"/opt/include/medlocalization.h"
"/opt/include/med.h"
"/opt/include/VolSurfUser.txx"
"/opt/include/IntersectorCU1D.hxx"
"/opt/include/Interpolation.txx"
"/opt/include/InterpKernelGeo2DEdgeInfLin.hxx"
"/opt/include/IntersectorCU3D.hxx"
"/opt/include/Intersector3DP0P1.txx"
"/opt/include/InterpKernelMeshQuality.hxx"
"/opt/include/Face.hxx"
"/opt/include/InterpolationCU.hxx"
"/opt/include/Interpolation3D2D.hxx"
"/opt/include/InterpolationCC.txx"
"/opt/include/Point.hxx"
"/opt/include/PolyhedronIntersectorP0P1.hxx"
"/opt/include/TransformedTriangle.hxx"
"/opt/include/PlanarIntersectorP1P0Bary.txx"
"/opt/include/NormalizedUnstructuredMesh.hxx"
"/opt/include/MEDCouplingFieldDiscretization.hxx"
"/opt/include/Interpolation1D.txx"
"/opt/include/PointLocator3DIntersectorP0P0.hxx"
"/opt/include/PointLocator2DIntersector.hxx"
"/opt/include/MEDCouplingMemArray.txx"
"/opt/include/Intersector3DP1P0.txx"
"/opt/include/PlanarIntersectorP0P1Bary.hxx"
"/opt/include/MEDCouplingNormalizedUnstructuredMesh.hxx"
"/opt/include/Interpolation2D1D.hxx"
"/opt/include/TriangulationIntersector.txx"
"/opt/include/MeshUtils.hxx"
"/opt/include/PlanarIntersectorP0P1.txx"
"/opt/include/VectorUtils.hxx"
"/opt/include/Interpolation2D.txx"
"/opt/include/MEDFileMeshLL.hxx"
"/opt/include/CdmathException.hxx"
"/opt/include/IntersectorCU2D.txx"
"/opt/include/InterpKernelGeo2DElementaryEdge.hxx"
"/opt/include/PointLocator3DIntersectorP1P0.txx"
"/opt/include/VTKNormalizedUnstructuredMesh.hxx"
"/opt/include/Intersector3DP1P0.hxx"
"/opt/include/MEDFileMesh.hxx"
"/opt/include/Field.hxx"
"/opt/include/Node.hxx"
"/opt/include/PlanarIntersector.txx"
"/opt/include/PlanarIntersector.hxx"
"/opt/include/MEDFileUtilities.hxx"
"/opt/include/InterpKernelGeo2DEdge.hxx"
"/opt/include/Interpolation2D.hxx"
"/opt/include/med.hf"
"/opt/include/MEDCouplingNormalizedUnstructuredMesh.txx"
"/opt/include/PointLocator3DIntersectorP1P0.hxx"
"/opt/include/MEDCouplingMemArray.hxx"
"/opt/include/medmesh.h"
"/opt/include/Polyhedron3D2DIntersectorP0P0.hxx"
"/opt/include/MEDCouplingFieldTemplate.hxx"
"/opt/include/BBTree.txx"
"/opt/include/MEDCoupling1GTUMesh.hxx"
"/opt/include/Geometric2DIntersector.txx"
"/opt/include/CurveIntersectorP0P0.txx"
"/opt/include/MEDCouplingTimeLabel.hxx"
"/opt/include/med_proto.h"
"/opt/include/InterpKernelHashFun.hxx"
"/opt/include/BoundingBox.hxx"
"/opt/include/MEDCouplingIMesh.hxx"
"/opt/include/MEDCouplingCMesh.hxx"
"/opt/include/medfamily.h"

